#include "Base/Provenance.h"

#include "Base/BuildInfo.h"       // generated by cmake/BuildInfo.cmake
#include "Base/Camera.h"
#include "Base/FDS_VARS.H"
#include "Base/FeatureFlags.h"

#include <cstdio>
#include <cstring>
#include <ctime>
#include <mutex>
#include <string>
#include <sys/stat.h>
#include <utility>
#include <vector>

#if defined(_WIN32)
#include "Base/WinCompat.h"   // realpath(), PATH_MAX
#include <direct.h>
#include <stdlib.h>
#define FDS_GETCWD _getcwd
extern "C" char **_environ;
#define FDS_ENVIRON _environ
#else
#include <limits.h>
#include <stdlib.h>
#include <unistd.h>
extern "C" char **environ;
#define FDS_GETCWD getcwd
#define FDS_ENVIRON environ
#endif

namespace fds {
namespace Provenance {
namespace {

std::mutex                                        g_mu;
std::vector<std::string>                          g_argv;
std::string                                       g_binPath;   // realpath(argv[0])
std::string                                       g_scene;
int                                               g_timeOverride = -1;
std::vector<std::pair<std::string, std::string>>  g_tags;

void jsonEscape(std::string &out, const char *s) {
    if (!s) return;
    for (const unsigned char *p = (const unsigned char *)s; *p; ++p) {
        switch (*p) {
        case '"':  out += "\\\""; break;
        case '\\': out += "\\\\"; break;
        case '\n': out += "\\n";  break;
        case '\r': out += "\\r";  break;
        case '\t': out += "\\t";  break;
        default:
            if (*p < 0x20) {
                char b[8];
                std::snprintf(b, sizeof b, "\\u%04x", (unsigned)*p);
                out += b;
            } else {
                out += (char)*p;
            }
        }
    }
}

void jsonStr(std::string &out, const char *s) {
    out += '"'; jsonEscape(out, s); out += '"';
}

// %.9g everywhere a float is a COORDINATE: 3 decimals is enough to re-frame a
// shot but not to reproduce a facing-threshold bug (a grazing face's N.A ~ 0
// test can flip inside the truncation error). Same reasoning, and the same
// format, as the [GREETS-CAM] line the G key prints.
void jsonF9(std::string &out, double v) {
    char b[40];
    std::snprintf(b, sizeof b, "%.9g", v);
    // JSON has no inf/nan; emit null rather than an unparseable document.
    if (std::strstr(b, "inf") || std::strstr(b, "nan")) { out += "null"; return; }
    out += b;
}

void isoUtc(std::string &out, std::time_t t) {
    char b[32] = {0};
    std::tm tmv{};
#if defined(_WIN32)
    gmtime_s(&tmv, &t);
#else
    gmtime_r(&t, &tmv);
#endif
    std::strftime(b, sizeof b, "%Y-%m-%dT%H:%M:%SZ", &tmv);
    out += b;
}

// The stem replacement: "a/b/greets_t005965_color.ppm" -> "a/b/greets_t005965_color.json".
// Only the LAST extension of the basename is replaced, so a dotted directory
// ("/tmp/run.1/x.ppm") is safe.
std::string sidecarPath(const char *imagePath) {
    std::string p(imagePath ? imagePath : "");
    const std::size_t slash = p.find_last_of("/\\");
    const std::size_t dot   = p.find_last_of('.');
    if (dot != std::string::npos && (slash == std::string::npos || dot > slash))
        p.erase(dot);
    p += ".json";
    return p;
}

// Env vars worth recording for reproduction: the FeatureFlags env aliases plus
// every raw snapshot/test env read in the tree (see .semgrep/revival.yml r1 for
// the census that produced these prefixes). Recorded ONLY when actually set, so
// a clean run carries an empty object.
const char *const kEnvPrefixes[] = {
    "FDS_", "FNTSNAP_", "CITYSNAP_", "XPARTEST_", "ENV", "GBUF_",
    "DUMP_", "EDIT_", "SURF_", "IMPORT_", "LIGHT", "PICK_", "SPLIT_",
    "SPOTEDIT_", "OBJSCALE_", "MAPVIZ_", "FOCUS_", "CLEARMAP_", "UV_TEST",
};

bool envInteresting(const char *kv) {
    for (const char *pre : kEnvPrefixes)
        if (std::strncmp(kv, pre, std::strlen(pre)) == 0) return true;
    return false;
}

} // namespace

void SetArgv(int argc, const char *const *argv) {
    std::lock_guard<std::mutex> lk(g_mu);
    g_argv.clear();
    for (int i = 0; i < argc; ++i) g_argv.emplace_back(argv[i] ? argv[i] : "");
    // Resolve argv[0] NOW: main() chdirs to the asset root a few lines later,
    // after which a relative "./DEMO" no longer names the binary that is
    // running, and the mtime stat below would silently record nothing.
    g_binPath.clear();
    if (argc > 0 && argv[0] && argv[0][0]) {
        char rp[4096];
        if (realpath(argv[0], rp)) g_binPath = rp;
        else                       g_binPath = argv[0];
    }
}

void SetScene(const char *scene) {
    std::lock_guard<std::mutex> lk(g_mu);
    g_scene = scene ? scene : "";
}

void SetTimeOverride(int t) {
    std::lock_guard<std::mutex> lk(g_mu);
    g_timeOverride = t;
}

void SetTag(const char *key, const char *value) {
    if (!key) return;
    std::lock_guard<std::mutex> lk(g_mu);
    for (auto &kv : g_tags)
        if (kv.first == key) { kv.second = value ? value : ""; return; }
    g_tags.emplace_back(key, value ? value : "");
}

void ClearTags() {
    std::lock_guard<std::mutex> lk(g_mu);
    g_tags.clear();
}

void BuildJson(std::string &out, const char *imagePath, int width, int height,
               const char *format) {
    std::lock_guard<std::mutex> lk(g_mu);
    char nb[64];

    out += "{\n  \"schema\": \"revival/snapshot-provenance\",\n";
    out += "  \"schema_version\": 1,\n";

    out += "  \"written_utc\": \"";
    isoUtc(out, std::time(nullptr));
    out += "\",\n";

    // ── image ────────────────────────────────────────────────────────
    out += "  \"image\": {\"path\": ";
    {
        std::string p(imagePath ? imagePath : "");
        const std::size_t slash = p.find_last_of("/\\");
        jsonStr(out, slash == std::string::npos ? p.c_str() : p.c_str() + slash + 1);
    }
    out += ", \"format\": "; jsonStr(out, format ? format : "ppm");
    std::snprintf(nb, sizeof nb, ", \"width\": %d, \"height\": %d}", width, height);
    out += nb; out += ",\n";

    // ── scene / time ─────────────────────────────────────────────────
    out += "  \"scene\": "; jsonStr(out, g_scene.c_str()); out += ",\n";
    const int t = (g_timeOverride >= 0) ? g_timeOverride : (int)Timer.load();
    std::snprintf(nb, sizeof nb, "  \"t\": %d,\n  \"frame_time\": %d,\n",
                  t, (int)g_FrameTime);
    out += nb;

    // ── camera ───────────────────────────────────────────────────────
    // pos = eye; fwd = Mat row 2 — exactly the pair FDS_GREETS_CAM consumes,
    // so `greets_cam` below can be pasted into a repro verbatim.
    out += "  \"camera\": ";
    if (View) {
        out += "{\"pos\": [";
        jsonF9(out, View->ISource.x); out += ", ";
        jsonF9(out, View->ISource.y); out += ", ";
        jsonF9(out, View->ISource.z); out += "], \"fwd\": [";
        jsonF9(out, View->Mat[2][0]); out += ", ";
        jsonF9(out, View->Mat[2][1]); out += ", ";
        jsonF9(out, View->Mat[2][2]); out += "], \"fov\": ";
        jsonF9(out, View->IFOV);
        out += ", \"greets_cam\": \"";
        std::snprintf(nb, sizeof nb, "%.9g,%.9g,%.9g",
                      (double)View->ISource.x, (double)View->ISource.y,
                      (double)View->ISource.z);
        out += nb; out += ',';
        std::snprintf(nb, sizeof nb, "%.9g,%.9g,%.9g",
                      (double)View->Mat[2][0], (double)View->Mat[2][1],
                      (double)View->Mat[2][2]);
        out += nb;
        out += "\"}";
    } else {
        out += "null";
    }
    out += ",\n";

    // ── argv + cwd ───────────────────────────────────────────────────
    out += "  \"argv\": [";
    for (std::size_t i = 0; i < g_argv.size(); ++i) {
        if (i) out += ", ";
        jsonStr(out, g_argv[i].c_str());
    }
    out += "],\n";
    {
        char cwd[4096] = {0};
        if (FDS_GETCWD(cwd, sizeof cwd)) { out += "  \"cwd\": "; jsonStr(out, cwd); }
        else                             { out += "  \"cwd\": null"; }
        out += ",\n";
    }

    // ── build ────────────────────────────────────────────────────────
    out += "  \"build\": {\"git_sha\": \"" FDS_BUILD_GIT_SHA "\", \"git_dirty\": ";
    out += (FDS_BUILD_GIT_DIRTY ? "true" : "false");
    out += ", \"git_describe\": \"" FDS_BUILD_GIT_SHA;
    out += (FDS_BUILD_GIT_DIRTY ? "+dirty" : "");
    out += "\", \"git_branch\": \"" FDS_BUILD_GIT_BRANCH
           "\", \"configured_utc\": \"" FDS_BUILD_CONFIGURED
           "\", \"source_dir\": \"" FDS_BUILD_SOURCE_DIR
           "\", \"binary_dir\": \"" FDS_BUILD_BINARY_DIR
           "\", \"build_type\": \"" FDS_BUILD_TYPE "\"},\n";

    // ── binary (real link/copy time — the configure stamp above is not it) ──
    out += "  \"binary\": ";
    if (!g_binPath.empty()) {
        struct stat st{};
        if (::stat(g_binPath.c_str(), &st) == 0) {
            out += "{\"path\": "; jsonStr(out, g_binPath.c_str());
            out += ", \"mtime_utc\": \"";
#if defined(__APPLE__)
            isoUtc(out, st.st_mtimespec.tv_sec);
#else
            isoUtc(out, st.st_mtime);
#endif
            std::snprintf(nb, sizeof nb, "\", \"size\": %lld}", (long long)st.st_size);
            out += nb;
        } else {
            out += "{\"path\": "; jsonStr(out, g_binPath.c_str());
            out += ", \"mtime_utc\": null, \"size\": null}";
        }
    } else {
        out += "null";
    }
    out += ",\n";

    // ── resolved flags that differ from their compile-time default ───
    out += "  \"flags\": ";
    {
        std::string flagsJson;
        FeatureFlags::dumpProvenanceFlagsJson(flagsJson);
        out += flagsJson;
    }
    out += ",\n";

    // ── env ──────────────────────────────────────────────────────────
    out += "  \"env\": {";
    {
        bool first = true;
        if (FDS_ENVIRON) {
            for (char **e = FDS_ENVIRON; *e; ++e) {
                if (!envInteresting(*e)) continue;
                const char *eq = std::strchr(*e, '=');
                if (!eq) continue;
                if (!first) out += ", ";
                first = false;
                std::string key(*e, eq - *e);
                jsonStr(out, key.c_str());
                out += ": ";
                jsonStr(out, eq + 1);
            }
        }
    }
    out += "}";

    // ── caller tags ──────────────────────────────────────────────────
    if (!g_tags.empty()) {
        out += ",\n  \"tags\": {";
        for (std::size_t i = 0; i < g_tags.size(); ++i) {
            if (i) out += ", ";
            jsonStr(out, g_tags[i].first.c_str());
            out += ": ";
            jsonStr(out, g_tags[i].second.c_str());
        }
        out += "}";
    }

    out += "\n}\n";
}

void WriteSidecar(const char *imagePath, int width, int height,
                  const char *format) {
    if (!imagePath) return;
    std::string json;
    BuildJson(json, imagePath, width, height, format);
    const std::string path = sidecarPath(imagePath);
    std::FILE *f = std::fopen(path.c_str(), "wb");
    if (!f) {
        std::fprintf(stderr, "[PROV] sidecar fopen('%s') failed\n", path.c_str());
        return;
    }
    std::fwrite(json.data(), 1, json.size(), f);
    std::fclose(f);
}

} // namespace Provenance
} // namespace fds
