#ifndef REVIVAL_TRIMESH_H
#define REVIVAL_TRIMESH_H

#include "BaseDefs.h"
#include "Color.h"
#include "Vertex.h"
#include "Face.h"
#include "Edge.h"
#include "Spline.h"
#include "Object.h"
#include "Matrix.h"

struct StaticShadowLightmap;  // FDS/Base/StaticShadowLightmap.h

#pragma pack(push, 1)

// [172 Bytes]
// Total: [220 Bytes + 84 Bytes per Vertex + 56 Bytes per Face +
//         16 Bytes * (Spline Keys + Hide Keys)]
struct TriMesh
{
    // strided array containing precalculated lighting.
    // uses packed dword BGRA to reduce memory read bandwidth usage
    // was optimized out for sse benefit
    Color			*SL             = nullptr;
    DWord            VIndex         = 0;     //Amount of Vertices on Mesh
    DWord            FIndex         = 0;     //Amount of Faces on Mesh
    DWord            EIndex         = 0;     //Amount of Edges on Mesh
    Vertex         * Verts          = nullptr;      //Vertex List
    Face           * Faces          = nullptr;      //Face List
    Edge           * Edges          = nullptr;      //Edge List
    Spline           Pos;        //Position Track Spline
    Spline           Scale;      //Scale Track Spline
    Spline           Rotate;     //Orientation Track Spline
    ObjectStatus   * Status         = nullptr;     //Hide Track (crap)
    ObjectStatus   * CurStat        = nullptr;    //Current Hide status
    Vector           IPos;       //Interpolated Position
    Vector           IScale;     //Interpolated Scale
    Quaternion       IRot;       //Interpolated Orientation (Quaternion)
    Matrix           UnscaledRotMat = { 0 };     // So yeah
    Matrix           RotMat         = { 0 };     //Interpolated Orientation (Matrix)
    Vector		     Heading;    // Generated by Position Track spline for meshes with the Align to path flag.
    Vector           BSphereCtr; // Bounding Sphere Center.
    Vector           BSphereScreenPos; // Bounding Sphere Center.
    float			 BSphereRadius  = 0.0f; // Bounding Sphere Radius.
    float            BSphereRad     = 0.0f; // Bounding Sphere Radius, squared. kept for backward compatibility until pipeline code is updated
    DWord            Flags          = 0;

    // Pre-baked per-face shadow factor for static omnis. Allocated by
    // LightmapBake_Static at scene init when --shadow-lightmap is on
    // and this mesh is "effectively static" (Pos/Rotate splines have
    // extent < threshold or NumKeys <= 1). nullptr → mesh runs the
    // legacy per-pixel cube-shadow tap path. See StaticShadowLightmap.h.
    StaticShadowLightmap *staticShadowLM = nullptr;

    // Index into Scene::staticLMTable. 0 = no lightmap (default). 1..N
    // = position of this mesh's lightmap pointer in the scene table.
    // Set by LightmapBake_Static; written by Mekalele into the G-buffer
    // per-pixel so the deferred kernel can look up the lightmap.
    uint16_t         staticLMMeshId = 0;

    // this is a temporary hack and will be removed in the future
    dword			 SortPriorityBias   = 0; // '1' value causes object to always be rendered first

    // Per-frame "seen this mesh in the deferred transparent peel order"
    // stamp. Compared against a frame counter to dedup TriMesh* entries
    // when building the per-object peel list from FList. Stale leftover
    // value across frames is fine — counter increments each frame, so
    // never collides.
    uint32_t         XparSeenFrame      = 0;

    TriMesh      * Next             = nullptr;
    TriMesh      * Prev             = nullptr;
};

#pragma pack(pop)

#endif //REVIVAL_TRIMESH_H
